language: node_js
services: mongodb
sudo: true
before_install:
  - source utils/install-conda.sh
  - npm install -g npm
    # Dependencies for zeromq
  - sudo apt-get install -y software-properties-common && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt update && sudo apt install -y g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
install:
  - npm install
  - conda env create --file environment.server.yml
script: source activate deepforge-keras-server && npm test
node_js:
  - "12"
