language: node_js
services: mongodb
sudo: true
before_install:
  - sudo apt-get update -q
  - sudo apt-get install python3-pip python-dev -y
  - pip3 install -U setuptools
  - pip3 install -U virtualenvwrapper
install:
  - pip3 install -r requirements.txt
  - npm install
node_js:
  - "8"
  - "10"
python:
  - "3.5"
