language: node_js
services: mongodb
sudo: true
before_install:
  - source utils/install-conda.sh
  - npm install -g npm
install:
  - npm install
  - conda env create --file environment.server.yml
script: source activate deepforge-keras-server && npm test
node_js:
  - "12"