// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.plugin.basePaths.push(__dirname + '/../node_modules/webgme-simple-nodes/src/plugins');
config.visualization.decoratorPaths.push(__dirname + '/../src/decorators');
config.visualization.decoratorPaths.push(__dirname + '/../node_modules/webgme-easydag/src/decorators');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/dev');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/base');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/keras');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/tests');



config.visualization.panelPaths.push(__dirname + '/../node_modules/webgme-easydag/src/visualizers/panels');
config.visualization.panelPaths.push(__dirname + '/../node_modules/webgme-autoviz/src/visualizers/panels');
config.visualization.panelPaths.push(__dirname + '/../src/visualizers/panels');




// Visualizer descriptors
config.visualization.visualizerDescriptors.push(__dirname + '/../src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'EllipseDecorator': 'node_modules/webgme-easydag/src/decorators/EllipseDecorator',
  'AutoViz': 'panels/AutoViz/AutoVizPanel',
  'EasyDAG': 'panels/EasyDAG/EasyDAGPanel',
  'SimpleNodes': 'node_modules/webgme-simple-nodes/src/plugins/SimpleNodes',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'panels/AutoViz': './node_modules/webgme-autoviz/src/visualizers/panels/AutoViz',
  'widgets/AutoViz': './node_modules/webgme-autoviz/src/visualizers/widgets/AutoViz',
  'panels/EasyDAG': './node_modules/webgme-easydag/src/visualizers/panels/EasyDAG',
  'widgets/EasyDAG': './node_modules/webgme-easydag/src/visualizers/widgets/EasyDAG',
  'webgme-simple-nodes': './node_modules/webgme-simple-nodes/src/common',
  'webgme-easydag': './node_modules/webgme-easydag/src/common',
  'webgme-autoviz': './node_modules/webgme-autoviz/src/common',
  'deepforge-keras': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/deepforge_keras';
validateConfig(config);
module.exports = config;
